name: release

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'

            - name: Install dependencies
              run: composer install --prefer-dist --no-interaction --no-ansi --no-progress --no-suggest

            - name: Install Box
              run: |
                  wget https://github.com/box-project/box/releases/download/3.13.0/box.phar
                  php box.phar compile

            - name: Getting tag name
              id: get-version
              run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}

            - name: Self-test
              run: ./akeneo-e3.phar --version

            - name: Create release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: ./akeneo-e3.phar
                  prerelease: true
