name: release

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Set Environment Variables
              uses: allenevans/set-env@v1.0.0
              with:
                  BOX_VERSION: '3.13.0'

            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'

            - name: Install dependencies
              run: composer install --prefer-dist --no-interaction --no-ansi --no-progress --no-suggest

            - name: Install Box
              run: |
                  wget \
                    "https://github.com/humbug/box/releases/download/${BOX_VERSION}/box.phar" \
                    --quiet \
                    -O ./box
                  php ./box/box.phar compile

            - name: Geting Tag Name
              id: get-version
              run: echo ::set-output name=version::${GITHUB_REF#refs/tags/}

            - name: Self-Test
              run: ./akeneo-e3.phar --version

            - name: Create Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  files: ./akeneo-e3.phar
                  prerelease: true
